version: "3"

services:
  db_mysql:
    image: mysql
    container_name: 'java-mysql'
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=ROOT
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB

  app:
    build: .
    container_name: 'java-app'
    restart: always
    ports:
      - "8080:8080"



